### ISSUE TITLE
It's not working for https://www.yahoo.com/

### ISSUE THREAD

**Issue by AlanKharebov** [m4bwav/get-title-at-url#3]
I am getting this error
Failed to load https://www.yahoo.com/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4201' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by m4bwav** [comment]
I'm not sure what's going on with the yahoo response.  I filed an issue with the request package to try and learn anything.  My package is just sorting through the response that it is given from request.

**Comment by MarkRogersEx** [comment]
I updated to the latest article title but it still isn't working.

**Comment by m4bwav** [comment]
I finally fixed this issue.
